# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultiplatformMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultiplatformMovies
  use_modular_headers!
  pod 'SDWebImage', :modular_headers => true

  target 'MultiplatformMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiplatformMoviesUITests' do
    # Pods for testing
  end

end
